### ISSUE TITLE
502 Bad Gateway on moodle 3.2

### ISSUE THREAD

**Issue by Andrewolico** [marxjohnson/moodle-block_messageteacher#23] opened 2017-01-13 17:50 UTC
Hi Mark,

Using a custom theme on moodle 3.2 I'm getting a 502 Bad Gateway error.

Thanks

Andrew

**Comment by marxjohnson** [comment] 2017-01-16 09:37
Hi Andrew,
Please can you give me a step-by-step guide to reproducing the error, including details about your server environment (OS, web server software etc)?
Thanks
Mark

**Comment by marxjohnson** [comment] 2019-09-17 07:49
I am closing this issue because it is 2 years old and has no further activity. If your problem still occurs with the latest version (2.5), please open a new issue.

**Closed by marxjohnson** 2019-09-17 07:49 UTC
